# Snapshot report for `test/external-assertions/test.js`

The actual snapshot is saved in `test.js.snap`.

Generated by [AVA](https://avajs.dev).

## node assertion

> Snapshot 1

    `␊
      ✘ [fail]: test Assertion failed␊
      ✘ [fail]: test async Assertion failed␊
      ─␊
    ␊
      test␊
    ␊
      assert-failure.js:6␊
    ␊
       5: test('test', () => {␊
       6:   assert(false);    ␊
       7: });                 ␊
    ␊
      Assertion failed: ␊
    ␊
      false == true␊
    ␊
      › file://assert-failure.js:6:2␊
    ␊
    ␊
    ␊
      test async␊
    ␊
      assert-failure.js:10␊
    ␊
        9: test('test async', async () => {       ␊
       10:   assert(await Promise.resolve(false));␊
       11: });                                    ␊
    ␊
      Assertion failed: ␊
    ␊
      false == true␊
    ␊
      › file://assert-failure.js:10:2␊
    ␊
      ─␊
    ␊
      2 tests failed`

## expect error

> Snapshot 1

    `␊
      ✘ [fail]: test Assertion failed␊
      ✘ [fail]: test async Assertion failed␊
      ─␊
    ␊
      test␊
    ␊
      expect-failure.js:5␊
    ␊
       4: test('test', () => {         ␊
       5:   expect(false).toBeTruthy();␊
       6: });                          ␊
    ␊
      Assertion failed: ␊
    ␊
      expect(received).toBeTruthy()␊
    ␊
      Received: false␊
    ␊
      › Received: false␊
      › file://expect-failure.js:5:16␊
    ␊
    ␊
    ␊
      test async␊
    ␊
      expect-failure.js:9␊
    ␊
       8: test('test async', async () => {                    ␊
       9:   expect(await Promise.resolve(false)).toBeTruthy();␊
       10: });                                                 ␊
    ␊
      Assertion failed: ␊
    ␊
      expect(received).toBeTruthy()␊
    ␊
      Received: false␊
    ␊
      › Received: false␊
      › file://expect-failure.js:9:39␊
    ␊
      ─␊
    ␊
      2 tests failed`
